project:
  type: website

website:
  title: "NAO Robust Detection notebook"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/naobservatory/rd-notebook
format:
  html:
    theme: sandstone
    css: styles.css



